config/routes.rb
Rails.application.routes.draw do
  
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :search_suggestions
      devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :boites do
    collection do
      match'search' => 'boites#index', :via => [:get,:post],:as =>:search
    end
  end
   root 'boites#index'

end

app/models/boite.rb
class Boite < ActiveRecord::Base

	geocoded_by :commune
	geocoded_by :full_address
	after_validation :geocode, if: ->(obj){ !obj.latitude.present? }

	def full_address
		"#{departement},#{zip},#{commune}"
	end

	

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |product|
	      csv << product.attributes.values_at(*column_names)
	    end
	  end
	end

end

app/controllers/boites_controller.rb
class BoitesController < ApplicationController
  before_action :set_boite, only: [:show, :edit, :update, :destroy]

  # GET /boites
  # GET /boites.json
  def index
   if params[:distance].present? && (params[:distance].to_i > 0)
      @search = Boite.near(params[:search], params[:distance] || 100).search(params[:q])
      @boites= @search.result.paginate(:page => params[:page], :per_page => 30)
      respond_to do |format|
        format.html
        format.xls { send_data @boites.to_csv(col_sep: "\t"), :filename => "Liste_boites.xls", :disposition => "attachment" }
      end
    else 
     @search = Boite.search(search_params)
     @boites = @search.result.paginate(:page => params[:page], :per_page => 30)

     #  @search.build_condition if @search.conditions.empty?
     @search.build_sort if @search.sorts.empty?
     respond_to do |format|
        format.html
        format.xls { send_data @search.result.to_csv(col_sep: "\t"), :filename => "Liste_boites.xls", :disposition => "attachment" }
      end
    end

  end

  # GET /boites/1
  # GET /boites/1.json
  def show
  end

  # GET /boites/new
  def new
    @boite = Boite.new
  end

  # GET /boites/1/edit
  def edit
  end

  # POST /boites
  # POST /boites.json
  def create
    @boite = Boite.new(boite_params)

    respond_to do |format|
      if @boite.save
        format.html { redirect_to @boite, notice: 'Boite was successfully created.' }
        format.json { render :show, status: :created, location: @boite }
      else
        format.html { render :new }
        format.json { render json: @boite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boites/1
  # PATCH/PUT /boites/1.json
  def update
    respond_to do |format|
      if @boite.update(boite_params)
        format.html { redirect_to @boite, notice: 'Boite was successfully updated.' }
        format.json { render :show, status: :ok, location: @boite }
      else
        format.html { render :edit }
        format.json { render json: @boite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boites/1
  # DELETE /boites/1.json
  def destroy
    @boite.destroy
    respond_to do |format|
      format.html { redirect_to boites_url, notice: 'Boite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 # CHECK THE SESSION FOR SEARCH PARAMETERS IS THEY AREN'T IN THE REQUEST
    def search_params
      if params[:q] == nil
          params[:q] = session[search_key]
      end
      if params[:q]
            session[search_key] = params[:q]
          end
          params[:q]
    end
    # DELETE SEARCH PARAMETERS FROM THE SESSION
    def clear_search_index
        if params[:search_cancel]
          params.delete(:search_cancel)
          if(!search_params.nil?)
              search_params.each do |key, param|
                  search_params[key] = nil
              end
          end
          # REMOVE FROM SESSION
          session.delete(search_key)
        end
    end
 
  protected
    # GENERATE A GENERIC SESSION KEY BASED ON TEH CONTROLLER NAME
    def search_key
      "#{location}_search".to_sym
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boite
      @boite = Boite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boite_params
      params.require(:boite).permit(:departement, :zip, :commune, :boite, :latitude, :longitude)
    end
end

app/helpers/boites_helper.rb
module BoitesHelper
end

app/views/boites/_form.html.erb
<%= form_for(@boite) do |f| %>
  <% if @boite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boite.errors.count, "error") %> prohibited this boite from being saved:</h2>

      <ul>
      <% @boite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :departement %><br>
    <%= f.text_field :departement %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :commune %><br>
    <%= f.text_field :commune %>
  </div>
  <div class="field">
    <%= f.label :boite %><br>
    <%= f.text_field :boite %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boites/edit.html.erb
<h1>Editing Boite</h1>

<%= render 'form' %>

<%= link_to 'Show', @boite %> |
<%= link_to 'Back', boites_path %>

app/views/boites/index.html.erb
<div id="post_content">
  
    <br><br>
    <h1>Liste des boites</h1>
    <span class="green">Nombre de boites : </span>
   


     <div class="row">
      <div class="col-xs-12 col-md-6">
        <div  class="post_wrapper">
          <h3>Recherche par rayon :</h3>
             <div class="form-group">
                <%= search_form_for @search do |f| %>
                  <%= label :lieu, "Lieu :" %>
                  <%= text_field_tag :search, params[:search], class: "form-control", :style => 'width:100%;'  %><br>
                  <%= label_tag :distance, "Rayon :"  %>
                  <%= text_field_tag :distance, params[:distance], class: "form-control", :style => 'width:100%;'  %>
              </div>
             <%= f.submit "Rechercher"%>
             <% end %>
          </div>
        </div>

        <div class="col-xs-12 col-md-6">
          <div  class="post_wrapper">
          <h3>Recherche par filtre :</h3>
            <div class="form-group">
             <%= search_form_for @search do |f| %>
              <%= f.text_field :commune_or_zip_has_any_term, id: "ville", class: "form-control", :placeholder => 'Sélectionner des communes ou entrer des codes postaux',:style => 'width:100%;' %><br>
             
             </div>
              <%= f.submit "Rechercher", class: 'submit' %>
            <% end %>
                
                
        </div>
      </div> 
   
         
          <div class="col-xs-12 col-md-12">
            <div class="post_wrapper">
                <table class="table">
                  <thead>
                    <tr>
                      <th><%= sort_link @search, :departement, "Departement" %></th>
                      <th><%= sort_link @search, :commune, "Commune" %></th>
                      <th><%= sort_link @search, :zip, "Code postale" %></th>
                      <th><%=  sort_link @search, :boite, "Boite" %></th>
                      <th colspan="3">
                      <p>
                        Télécharger :
                        <%= link_to "Excel", search_boites_path(params.merge(format: "xls")) %>
                      </p>
                      </th>
                    </tr>
                  </thead>
                
                  <tbody>

                   

                    <% @boites.each do |boite| %>

                      <tr>
                        <td><%= boite.departement %></td>
                        <td><%= boite.commune %></td>
                        <td><%= boite.zip %></td>
                        <td><%= boite.boite %></td>
                        <td width="20px"></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <br>
  
     <%= will_paginate @location, renderer: BootstrapPagination::Rails %>
   
</div>

<script type="text/javascript">
      $('#ville').tokenfield({
       autocomplete: {
         source: "/search_suggestions",
        //  delay: 100
       },
        //showAutocompleteOnFocus: true
    })

     

     // $('#code_postal').tokenfield()

     
    </script>

app/views/boites/new.html.erb
<h1>New Boite</h1>

<%= render 'form' %>

<%= link_to 'Back', boites_path %>

app/views/boites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departement:</strong>
  <%= @boite.departement %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @boite.zip %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @boite.commune %>
</p>

<p>
  <strong>Boite:</strong>
  <%= @boite.boite %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @boite.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @boite.longitude %>
</p>

<%= link_to 'Edit', edit_boite_path(@boite) %> |
<%= link_to 'Back', boites_path %>